import 'package:flutter/material.dart';

abstract final class IconMapper {
  static IconData getIcon(String key) {
    switch (key) {
      case 'home':
        return Icons.home_outlined;
      case 'bolt':
        return Icons.bolt_outlined;
      case 'restaurant':
        return Icons.restaurant_outlined;
      case 'car':
        return Icons.directions_car_outlined;
      case 'health':
        return Icons.favorite_outline;
      case 'education':
        return Icons.school_outlined;
      case 'shopping':
        return Icons.shopping_bag_outlined;
      case 'entertainment':
        return Icons.movie_outlined;
      case 'finance':
        return Icons.account_balance_outlined;
      case 'family':
        return Icons.people_outline;
      case 'work':
        return Icons.work_outline;
      case 'palette':
        return Icons.palette_outlined;
      case 'kitchen':
        return Icons.kitchen_outlined;
      case 'receipt':
        return Icons.receipt_outlined;
      case 'cleaning_services':
        return Icons.cleaning_services_outlined;
      case 'build':
        return Icons.build_outlined;
      case 'chair':
        return Icons.chair_outlined;
      case 'handyman':
        return Icons.handyman_outlined;
      case 'water_drop':
        return Icons.water_drop_outlined;
      case 'tv':
        return Icons.tv_outlined;
      case 'local_fire_department':
        return Icons.local_fire_department_outlined;
      case 'wifi':
        return Icons.wifi_outlined;
      case 'electric_bolt':
        return Icons.electric_bolt_outlined;
      case 'cloud':
        return Icons.cloud_outlined;
      case 'play_circle':
        return Icons.play_circle_outline;
      case 'phone':
        return Icons.phone_outlined;
      case 'coffee':
        return Icons.coffee_outlined;
      case 'set_meal':
        return Icons.set_meal_outlined;
      case 'delivery_dining':
        return Icons.delivery_dining_outlined;
      case 'bakery_dining':
        return Icons.bakery_dining_outlined;
      case 'restaurant_menu':
        return Icons.restaurant_menu_outlined;
      case 'shopping_cart':
        return Icons.shopping_cart_outlined;
      case 'eco':
        return Icons.eco_outlined;
      case 'local_gas_station':
        return Icons.local_gas_station_outlined;
      case 'local_parking':
        return Icons.local_parking_outlined;
      case 'toll':
        return Icons.toll_outlined;
      case 'security':
        return Icons.security_outlined;
      case 'local_taxi':
        return Icons.local_taxi_outlined;
      case 'directions_bus':
        return Icons.directions_bus_outlined;
      case 'emoji_transportation':
        return Icons.emoji_transportation_outlined;
      case 'medical_services':
        return Icons.medical_services_outlined;
      case 'science':
        return Icons.science_outlined;
      case 'medication':
        return Icons.medication_outlined;
      case 'health_and_safety':
        return Icons.health_and_safety_outlined;
      case 'mood':
        return Icons.mood_outlined;
      case 'visibility':
        return Icons.visibility_outlined;
      case 'menu_book':
        return Icons.menu_book_outlined;
      case 'payments':
        return Icons.payments_outlined;
      case 'book':
        return Icons.book_outlined;
      case 'edit':
        return Icons.edit_outlined;
      case 'hiking':
        return Icons.hiking_outlined;
      case 'language':
        return Icons.language_outlined;
      case 'card_giftcard':
        return Icons.card_giftcard_outlined;
      case 'checkroom':
        return Icons.checkroom_outlined;
      case 'devices':
        return Icons.devices_outlined;
      case 'movie':
        return Icons.movie_outlined;
      case 'event':
        return Icons.event_outlined;
      case 'sports_esports':
        return Icons.sports_esports_outlined;
      case 'nightlife':
        return Icons.nightlife_outlined;
      case 'flight':
        return Icons.flight_outlined;
      case 'account_balance_wallet':
        return Icons.account_balance_wallet_outlined;
      case 'receipt_long':
        return Icons.receipt_long_outlined;
      case 'percent':
        return Icons.percent_outlined;
      case 'business':
        return Icons.business_outlined;
      case 'credit_card':
        return Icons.credit_card_outlined;
      case 'self_improvement':
        return Icons.self_improvement_outlined;
      case 'child_care':
        return Icons.child_care_outlined;
      case 'child_friendly':
        return Icons.child_friendly_outlined;
      case 'pets':
        return Icons.pets_outlined;
      case 'lunch_dining':
        return Icons.lunch_dining_outlined;
      case 'commute':
        return Icons.commute_outlined;
      case 'volunteer_activism':
        return Icons.volunteer_activism_outlined;
      case 'warning':
        return Icons.warning_amber_outlined;
      case 'more_horiz':
        return Icons.more_horiz;
      case 'storefront':
        return Icons.storefront_outlined;
      case 'savings':
        return Icons.savings_outlined;
      case 'shield':
        return Icons.shield_outlined;
      case 'category':
      default:
        return Icons.category_outlined;
    }
  }
}
