import '../../../../app/app_strings.dart';

class DefaultCategoryNameLocalizer {
  const DefaultCategoryNameLocalizer._();

  static String localize(String name, AppStrings strings) {
    if (strings.isEnglish) {
      return _esToEn[_normalize(name)] ?? name;
    }
    if (strings.isPortugueseBrazil) {
      return _esToPtBr[_normalize(name)] ?? name;
    }
    return name;
  }

  static final Map<String, String> _esToPtBr = {
    _normalize('Sueldo'): 'Salário',
    _normalize('Freelance'): 'Freelance',
    _normalize('Venta'): 'Venda',
    _normalize('Hogar'): 'Casa',
    _normalize('Servicios'): 'Serviços',
    _normalize('Alimentos'): 'Alimentação',
    _normalize('Alimentación'): 'Alimentação',
    _normalize('Transporte'): 'Transporte',
    _normalize('Salud'): 'Saúde',
    _normalize('Educación'): 'Educação',
    _normalize('Compras'): 'Compras',
    _normalize('Ocio'): 'Lazer',
    _normalize('Finanzas'): 'Finanças',
    _normalize('Familia'): 'Família',
    _normalize('Trabajo'): 'Trabalho',
    _normalize('Otros'): 'Outros',
    _normalize('Ahorro general'): 'Economias gerais',
    _normalize('Fondo de emergencia'): 'Reserva de emergência',
    _normalize('Viaje'): 'Viagem',
    _normalize('Alquiler'): 'Aluguel',
    _normalize('Decoración'): 'Decoração',
    _normalize('Electrodomésticos'): 'Eletrodomésticos',
    _normalize('Expensas'): 'Condomínio',
    _normalize('Limpieza'): 'Limpeza',
    _normalize('Mantenimiento'): 'Manutenção',
    _normalize('Mantenimiento del vehículo'): 'Manutenção do veículo',
    _normalize('Muebles'): 'Móveis',
    _normalize('Reparaciones'): 'Reparos',
    _normalize('Agua'): 'Água',
    _normalize('Cable / TV'): 'TV a cabo',
    _normalize('Gas'): 'Gás',
    _normalize('Internet'): 'Internet',
    _normalize('Luz'): 'Luz',
    _normalize('Nube / Apps'): 'Nuvem / Apps',
    _normalize('Streaming'): 'Streaming',
    _normalize('Teléfono'): 'Telefone',
    _normalize('Cafetería'): 'Cafeteria',
    _normalize('Carnicería'): 'Açougue',
    _normalize('Delivery'): 'Delivery',
    _normalize('Panadería'): 'Padaria',
    _normalize('Restaurantes'): 'Restaurantes',
    _normalize('Supermercado'): 'Supermercado',
    _normalize('Verdulería'): 'Hortifruti',
    _normalize('Combustible'): 'Combustível',
    _normalize('Estacionamiento'): 'Estacionamento',
    _normalize('Peajes'): 'Pedágios',
    _normalize('Seguro del auto'): 'Seguro do carro',
    _normalize('Taxi / Remis'): 'Táxi / App',
    _normalize('Transporte público'): 'Transporte público',
    _normalize('Uber / Cabify'): 'Uber / Cabify',
    _normalize('Consultas médicas'): 'Consultas médicas',
    _normalize('Estudios'): 'Exames',
    _normalize('Medicamentos'): 'Medicamentos',
    _normalize('Obra social / Prepaga'): 'Plano de saúde',
    _normalize('Odontología'): 'Odontologia',
    _normalize('Óptica'): 'Ótica',
    _normalize('Cursos'): 'Cursos',
    _normalize('Cuotas'): 'Mensalidades',
    _normalize('Libros'): 'Livros',
    _normalize('Materiales'): 'Materiais',
    _normalize('Suscripciones educativas'): 'Assinaturas educativas',
    _normalize('Calzado'): 'Calçados',
    _normalize('Compras online'): 'Compras online',
    _normalize('Regalos'): 'Presentes',
    _normalize('Ropa'): 'Roupas',
    _normalize('Tecnología'): 'Tecnologia',
    _normalize('Cine'): 'Cinema',
    _normalize('Eventos'): 'Eventos',
    _normalize('Hobbies'): 'Hobbies',
    _normalize('Juegos'): 'Jogos',
    _normalize('Salidas'): 'Saídas',
    _normalize('Vacaciones'): 'Férias',
    _normalize('Comisiones bancarias'): 'Tarifas bancárias',
    _normalize('Impuestos'): 'Impostos',
    _normalize('Intereses'): 'Juros',
    _normalize('Monotributo / Autónomos'): 'Impostos de autônomo',
    _normalize('Tarjetas de crédito'): 'Cartões de crédito',
    _normalize('Cuidado personal'): 'Cuidados pessoais',
    _normalize('Guardería / Colegio'): 'Creche / Escola',
    _normalize('Hijos'): 'Filhos',
    _normalize('Mascotas'): 'Pets',
    _normalize('Capacitación'): 'Capacitação',
    _normalize('Comidas laborales'): 'Refeições de trabalho',
    _normalize('Herramientas'): 'Ferramentas',
    _normalize('Transporte laboral'): 'Transporte de trabalho',
    _normalize('Donaciones'): 'Doações',
    _normalize('Imprevistos'): 'Imprevistos',
    _normalize('Varios'): 'Diversos',
  };

  static final Map<String, String> _esToEn = {
    _normalize('Sueldo'): 'Salary',
    _normalize('Freelance'): 'Freelance',
    _normalize('Venta'): 'Sale',
    _normalize('Hogar'): 'Home',
    _normalize('Servicios'): 'Services',
    _normalize('Alimentos'): 'Food',
    _normalize('Alimentación'): 'Food',
    _normalize('Transporte'): 'Transport',
    _normalize('Salud'): 'Health',
    _normalize('Educación'): 'Education',
    _normalize('Compras'): 'Shopping',
    _normalize('Ocio'): 'Leisure',
    _normalize('Finanzas'): 'Finance',
    _normalize('Familia'): 'Family',
    _normalize('Trabajo'): 'Work',
    _normalize('Otros'): 'Other',
    _normalize('Ahorro general'): 'General savings',
    _normalize('Fondo de emergencia'): 'Emergency fund',
    _normalize('Viaje'): 'Travel',
    _normalize('Alquiler'): 'Rent',
    _normalize('Decoración'): 'Decor',
    _normalize('Electrodomésticos'): 'Appliances',
    _normalize('Expensas'): 'Condo fees',
    _normalize('Limpieza'): 'Cleaning',
    _normalize('Mantenimiento'): 'Maintenance',
    _normalize('Mantenimiento del vehículo'): 'Vehicle maintenance',
    _normalize('Muebles'): 'Furniture',
    _normalize('Reparaciones'): 'Repairs',
    _normalize('Agua'): 'Water',
    _normalize('Cable / TV'): 'Cable / TV',
    _normalize('Gas'): 'Gas',
    _normalize('Internet'): 'Internet',
    _normalize('Luz'): 'Electricity',
    _normalize('Nube / Apps'): 'Cloud / Apps',
    _normalize('Streaming'): 'Streaming',
    _normalize('Teléfono'): 'Phone',
    _normalize('Cafetería'): 'Coffee shop',
    _normalize('Carnicería'): 'Butcher',
    _normalize('Delivery'): 'Delivery',
    _normalize('Panadería'): 'Bakery',
    _normalize('Restaurantes'): 'Restaurants',
    _normalize('Supermercado'): 'Supermarket',
    _normalize('Verdulería'): 'Produce store',
    _normalize('Combustible'): 'Fuel',
    _normalize('Estacionamiento'): 'Parking',
    _normalize('Peajes'): 'Tolls',
    _normalize('Seguro del auto'): 'Car insurance',
    _normalize('Taxi / Remis'): 'Taxi / Cab',
    _normalize('Transporte público'): 'Public transport',
    _normalize('Uber / Cabify'): 'Uber / Cabify',
    _normalize('Consultas médicas'): 'Medical appointments',
    _normalize('Estudios'): 'Medical tests',
    _normalize('Medicamentos'): 'Medication',
    _normalize('Obra social / Prepaga'): 'Health insurance',
    _normalize('Odontología'): 'Dentistry',
    _normalize('Óptica'): 'Optical',
    _normalize('Cursos'): 'Courses',
    _normalize('Cuotas'): 'Tuition',
    _normalize('Libros'): 'Books',
    _normalize('Materiales'): 'Supplies',
    _normalize('Suscripciones educativas'): 'Educational subscriptions',
    _normalize('Calzado'): 'Footwear',
    _normalize('Compras online'): 'Online shopping',
    _normalize('Regalos'): 'Gifts',
    _normalize('Ropa'): 'Clothing',
    _normalize('Tecnología'): 'Technology',
    _normalize('Cine'): 'Cinema',
    _normalize('Eventos'): 'Events',
    _normalize('Hobbies'): 'Hobbies',
    _normalize('Juegos'): 'Games',
    _normalize('Salidas'): 'Going out',
    _normalize('Vacaciones'): 'Holidays',
    _normalize('Comisiones bancarias'): 'Bank fees',
    _normalize('Impuestos'): 'Taxes',
    _normalize('Intereses'): 'Interest',
    _normalize('Monotributo / Autónomos'): 'Self-employed taxes',
    _normalize('Tarjetas de crédito'): 'Credit cards',
    _normalize('Cuidado personal'): 'Personal care',
    _normalize('Guardería / Colegio'): 'Daycare / School',
    _normalize('Hijos'): 'Children',
    _normalize('Mascotas'): 'Pets',
    _normalize('Capacitación'): 'Training',
    _normalize('Comidas laborales'): 'Work meals',
    _normalize('Herramientas'): 'Tools',
    _normalize('Transporte laboral'): 'Work transport',
    _normalize('Donaciones'): 'Donations',
    _normalize('Imprevistos'): 'Unexpected expenses',
    _normalize('Varios'): 'Miscellaneous',
  };

  static String _normalize(String value) {
    final lower = value.trim().toLowerCase();
    final buffer = StringBuffer();
    for (final rune in lower.runes) {
      buffer.write(_replacementByRune[rune] ?? String.fromCharCode(rune));
    }
    return buffer.toString().replaceAll(RegExp(r'\s+'), ' ');
  }

  static const Map<int, String> _replacementByRune = {
    225: 'a', // á
    233: 'e', // é
    237: 'i', // í
    243: 'o', // ó
    250: 'u', // ú
    252: 'u', // ü
    241: 'n', // ñ
  };
}
